"""add phone and registration intake fields

Revision ID: 1df5d3afc741
Revises: 826673693392
Create Date: 2026-09-19 13:02:10.183744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df5d3afc741'
down_revision: Union[str, Sequence[str], None] = '826673693392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_histories', sa.Column('current_complaint_hpi', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('past_medical_history', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('past_medication_history', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('allergy_history', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('diet', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('appetite', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('sleep', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('exercise', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('bowel_bladder', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('habits', sa.Text(), nullable=True))
    op.add_column('medical_histories', sa.Column('family_history', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('patient_profiles', sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('patient_profiles', sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'phone')
    op.drop_column('patient_profiles', 'weight_kg')
    op.drop_column('patient_profiles', 'height_cm')
    op.drop_column('patient_profiles', 'date_of_birth')
    op.drop_column('medical_histories', 'family_history')
    op.drop_column('medical_histories', 'habits')
    op.drop_column('medical_histories', 'bowel_bladder')
    op.drop_column('medical_histories', 'exercise')
    op.drop_column('medical_histories', 'sleep')
    op.drop_column('medical_histories', 'appetite')
    op.drop_column('medical_histories', 'diet')
    op.drop_column('medical_histories', 'allergy_history')
    op.drop_column('medical_histories', 'past_medication_history')
    op.drop_column('medical_histories', 'past_medical_history')
    op.drop_column('medical_histories', 'current_complaint_hpi')
    # ### end Alembic commands ###
