"""Export Mendix response examples from the real FastAPI contract.

The success example is generated by calling the real application with a real local
X-ray image path passed through --image. Error examples are generated through the
same FastAPI route and validators. No fake prediction service is used here.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from fastapi.testclient import TestClient

from lung_xray_api.main import create_app

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PREDICT_PATH = "/api/v1/predict"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export Mendix handoff JSON examples.")
    parser.add_argument(
        "--image",
        type=Path,
        required=True,
        help="Path to a valid local X-ray image used for the prediction-success example.",
    )
    return parser.parse_args()


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def _assert_response(name: str, status_code: int, expected: int, payload: Any) -> None:
    if status_code != expected:
        raise RuntimeError(f"{name} expected HTTP {expected}, got {status_code}: {payload}")


def main() -> int:
    args = parse_args()
    image_path = args.image
    if not image_path.is_file():
        raise FileNotFoundError(f"Valid --image file is required: {image_path}")

    output_dir = PROJECT_ROOT / "handoff" / "mendix" / "examples"
    output_dir.mkdir(parents=True, exist_ok=True)

    image_bytes = image_path.read_bytes()
    app = create_app()
    with TestClient(app) as client:
        success = client.post(
            PREDICT_PATH,
            files={"file": (image_path.name, image_bytes, "image/jpeg")},
        )
        invalid = client.post(
            PREDICT_PATH,
            files={"file": ("invalid.txt", b"not an image", "text/plain")},
        )
        too_large = client.post(
            PREDICT_PATH,
            files={"file": ("oversized.jpg", b"x" * (11 * 1024 * 1024), "image/jpeg")},
        )

    not_ready_app = create_app(load_model=False)
    with TestClient(not_ready_app) as client:
        not_ready = client.post(
            PREDICT_PATH,
            files={"file": (image_path.name, image_bytes, "image/jpeg")},
        )

    responses = {
        "prediction-success.json": (success, 200),
        "invalid-image.json": (invalid, 400),
        "file-too-large.json": (too_large, 400),
        "model-not-ready.json": (not_ready, 503),
    }

    for name, (response, expected_status) in responses.items():
        payload = response.json()
        _assert_response(name, response.status_code, expected_status, payload)
        _write_json(output_dir / name, payload)

    print(output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())